"use client";

import Link from "next/link";
import { useLanguage } from "./LanguageProvider";

const content = {
    en: {
        title: "PRIVACY",
        intro: "This privacy policy explains how PTYTSCH (ptytsch.de) handles your data.",
        sections: [
            {
                heading: "Data controller",
                text: "Roman Ponomarev, Munich, Germany. Contact: hi@ptytsch.de",
            },
            {
                heading: "Hosting",
                text: "This website is hosted on Vercel (Vercel Inc., San Francisco, CA, USA). When you visit the site, Vercel may process your IP address and technical metadata (browser type, operating system, referrer) to deliver the page. This processing is based on our legitimate interest in providing the website (Art. 6(1)(f) GDPR). Vercel's privacy policy: https://vercel.com/legal/privacy-policy",
            },
            {
                heading: "Analytics",
                text: "We use Vercel Web Analytics and Speed Insights. These tools do not use cookies, do not track individual users, and do not collect personal data. They provide aggregated, anonymised metrics about page views and performance. No data is shared with third parties for advertising purposes. Legal basis: legitimate interest in understanding site usage (Art. 6(1)(f) GDPR).",
            },
            {
                heading: "Cookies",
                text: "This website uses a single functional cookie: \"ptytsch_lang\" stores your language preference (en, de, or ru). It expires after 365 days. This cookie is strictly necessary for the website to function in your preferred language and does not require consent under GDPR. No tracking cookies, advertising cookies, or third-party cookies are used.",
            },
            {
                heading: "Data we do not collect",
                text: "We do not collect personal data through forms, registrations, or accounts. We do not use comment systems, social media plugins, or embedded content from third parties. We do not process payment information. We do not build user profiles or use tracking pixels.",
            },
            {
                heading: "Your rights",
                text: "Under GDPR you have the right to: access your data, request correction or deletion, restrict processing, data portability, and object to processing. You also have the right to lodge a complaint with a supervisory authority. Since we do not store personal data beyond what is described above, most of these rights are already fulfilled by design. Contact: hi@ptytsch.de",
            },
            {
                heading: "AI-generated content",
                text: "All articles on this website are generated by artificial intelligence (Anthropic Claude). No personal data of website visitors is used in the content generation process. Event information is sourced from publicly available data.",
            },
        ],
    },
    de: {
        title: "DATENSCHUTZ",
        intro: "Diese Datenschutzerklärung erläutert, wie PTYTSCH (ptytsch.de) mit Ihren Daten umgeht.",
        sections: [
            {
                heading: "Verantwortlicher",
                text: "Roman Ponomarev, München, Deutschland. Kontakt: hi@ptytsch.de",
            },
            {
                heading: "Hosting",
                text: "Diese Website wird bei Vercel (Vercel Inc., San Francisco, CA, USA) gehostet. Beim Besuch der Seite kann Vercel Ihre IP-Adresse und technische Metadaten (Browsertyp, Betriebssystem, Referrer) verarbeiten, um die Seite auszuliefern. Die Verarbeitung erfolgt auf Grundlage unseres berechtigten Interesses an der Bereitstellung der Website (Art. 6 Abs. 1 lit. f DSGVO). Datenschutzerklärung von Vercel: https://vercel.com/legal/privacy-policy",
            },
            {
                heading: "Analyse",
                text: "Wir verwenden Vercel Web Analytics und Speed Insights. Diese Tools verwenden keine Cookies, verfolgen keine einzelnen Nutzer und erheben keine personenbezogenen Daten. Sie liefern aggregierte, anonymisierte Kennzahlen über Seitenaufrufe und Performance. Keine Daten werden zu Werbezwecken an Dritte weitergegeben. Rechtsgrundlage: berechtigtes Interesse an der Analyse der Websitenutzung (Art. 6 Abs. 1 lit. f DSGVO).",
            },
            {
                heading: "Cookies",
                text: "Diese Website verwendet einen einzigen funktionalen Cookie: \"ptytsch_lang\" speichert Ihre Sprachpräferenz (en, de oder ru). Er läuft nach 365 Tagen ab. Dieser Cookie ist für die Funktion der Website in Ihrer bevorzugten Sprache unbedingt erforderlich und bedarf gemäß DSGVO keiner Einwilligung. Es werden keine Tracking-Cookies, Werbe-Cookies oder Drittanbieter-Cookies verwendet.",
            },
            {
                heading: "Daten, die wir nicht erheben",
                text: "Wir erheben keine personenbezogenen Daten über Formulare, Registrierungen oder Konten. Wir verwenden keine Kommentarsysteme, Social-Media-Plugins oder eingebettete Inhalte von Drittanbietern. Wir verarbeiten keine Zahlungsinformationen. Wir erstellen keine Nutzerprofile und verwenden keine Tracking-Pixel.",
            },
            {
                heading: "Ihre Rechte",
                text: "Nach der DSGVO haben Sie das Recht auf: Auskunft, Berichtigung oder Löschung Ihrer Daten, Einschränkung der Verarbeitung, Datenübertragbarkeit und Widerspruch gegen die Verarbeitung. Sie haben außerdem das Recht, Beschwerde bei einer Aufsichtsbehörde einzulegen. Da wir über das oben Beschriebene hinaus keine personenbezogenen Daten speichern, sind die meisten dieser Rechte bereits durch das Design erfüllt. Kontakt: hi@ptytsch.de",
            },
            {
                heading: "KI-generierte Inhalte",
                text: "Alle Artikel auf dieser Website werden von künstlicher Intelligenz (Anthropic Claude) erstellt. Für die Inhaltserstellung werden keine personenbezogenen Daten der Website-Besucher verwendet. Veranstaltungsinformationen stammen aus öffentlich zugänglichen Daten.",
            },
        ],
    },
    ru: {
        title: "КОНФИДЕНЦИАЛЬНОСТЬ",
        intro: "Эта политика конфиденциальности объясняет, как PTYTSCH (ptytsch.de) обращается с вашими данными.",
        sections: [
            {
                heading: "Ответственный",
                text: "Roman Ponomarev, Мюнхен, Германия. Контакт: hi@ptytsch.de",
            },
            {
                heading: "Хостинг",
                text: "Сайт размещён на Vercel (Vercel Inc., Сан-Франциско, Калифорния, США). При посещении сайта Vercel может обрабатывать ваш IP-адрес и технические метаданные (тип браузера, ОС, реферер) для доставки страницы. Обработка основана на нашем законном интересе в предоставлении сайта (ст. 6(1)(f) GDPR). Политика конфиденциальности Vercel: https://vercel.com/legal/privacy-policy",
            },
            {
                heading: "Аналитика",
                text: "Мы используем Vercel Web Analytics и Speed Insights. Эти инструменты не используют cookies, не отслеживают отдельных пользователей и не собирают персональные данные. Они предоставляют агрегированные анонимные метрики о посещениях и производительности. Данные не передаются третьим лицам для рекламных целей. Правовое основание: законный интерес в понимании использования сайта (ст. 6(1)(f) GDPR).",
            },
            {
                heading: "Cookies",
                text: "Этот сайт использует один функциональный cookie: \"ptytsch_lang\" хранит ваш выбор языка (en, de или ru). Срок действия — 365 дней. Этот cookie строго необходим для работы сайта на выбранном языке и не требует согласия по GDPR. Никаких отслеживающих, рекламных или сторонних cookies не используется.",
            },
            {
                heading: "Данные, которые мы не собираем",
                text: "Мы не собираем персональные данные через формы, регистрации или аккаунты. Мы не используем системы комментариев, плагины социальных сетей или встроенный контент третьих сторон. Мы не обрабатываем платёжную информацию. Мы не строим профили пользователей и не используем пиксели отслеживания.",
            },
            {
                heading: "Ваши права",
                text: "По GDPR вы имеете право на: доступ к данным, их исправление или удаление, ограничение обработки, переносимость данных и возражение против обработки. Вы также можете подать жалобу в надзорный орган. Поскольку мы не храним персональные данные сверх описанного выше, большинство этих прав уже обеспечены конструктивно. Контакт: hi@ptytsch.de",
            },
            {
                heading: "Контент, созданный ИИ",
                text: "Все статьи на этом сайте созданы искусственным интеллектом (Anthropic Claude). Персональные данные посетителей сайта не используются при генерации контента. Информация о событиях получена из открытых источников.",
            },
        ],
    },
};

export default function PrivacyContent() {
    const { lang } = useLanguage();
    const t = content[lang];

    return (
        <div className="max-w-3xl mx-auto pt-4 md:pt-8">
            <h1
                className="text-6xl md:text-8xl lg:text-[10rem] leading-[0.85] mb-12 md:mb-16"
                style={{ fontFamily: "var(--font-display)" }}
            >
                {t.title}
            </h1>

            <p className="text-xl md:text-2xl leading-relaxed mb-10 md:mb-12">
                {t.intro}
            </p>

            <div className="space-y-10 md:space-y-12">
                {t.sections.map((section, i) => (
                    <section key={i}>
                        <h2 className="font-mono text-xs tracking-widest uppercase mb-4" style={{ color: "#999999" }}>
                            {section.heading}
                        </h2>
                        <p className="text-lg md:text-xl leading-relaxed">
                            {section.text}
                        </p>
                    </section>
                ))}
            </div>

            <div className="mt-16 md:mt-24 pt-8 border-t-4 border-black">
                <Link
                    href={`/${lang}/`}
                    className="font-mono text-sm tracking-wide no-underline transition-colors duration-100"
                    style={{ color: "#999999", textDecoration: "none" }}
                    onMouseEnter={(e) => (e.currentTarget.style.color = "#000000")}
                    onMouseLeave={(e) => (e.currentTarget.style.color = "#999999")}
                >
                    ← PTYTSCH
                </Link>
            </div>
        </div>
    );
}
